version: "3.8" # Cette ligne peut être supprimée si vous voulez (optionnelle)

services:
  mysql:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  php:
    build: ./backend
    env_file: .env
    ports:
      - "${PHP_PORT}:80"
    depends_on:
      - mysql

  flutter:
    build: ./frontend
    env_file: .env
    ports:
      - "${FLUTTER_PORT}:5000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
